// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetRowCount(arg1:string):Promise<number>;

export function GetTableData(arg1:string,arg2:number):Promise<Array<Record<string, any>>>;

export function GetTableSchema(arg1:string):Promise<Array<backend.ColumnSchema>>;

export function LoadDatabase(arg1:string):Promise<Array<string>>;
