// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRowCount(arg1) {
  return window['go']['main']['App']['GetRowCount'](arg1);
}

export function GetTableData(arg1, arg2) {
  return window['go']['main']['App']['GetTableData'](arg1, arg2);
}

export function GetTableSchema(arg1) {
  return window['go']['main']['App']['GetTableSchema'](arg1);
}

export function LoadDatabase(arg1) {
  return window['go']['main']['App']['LoadDatabase'](arg1);
}
