// NIVEL BASICO: Componente principal React
// useState gerencia estado (variaveis que re-renderizam quando mudam)

import { useState } from 'react';
import './App.css';

// NIVEL BASICO: Declaracao TypeScript para metodos Go expostos pelo Wails
// NIVEL TECNICO: Will be auto-generated by wails dev, declaring manually for now
declare global {
  interface Window {
    go: {
      main: {
        App: {
          LoadDatabase: (dbPath: string) => Promise<string[]>;
          GetTableData: (tableName: string, limit: number) => Promise<Record<string, any>[]>;
          GetRowCount: (tableName: string) => Promise<number>;
        };
      };
    };
  }
}

function App() {
  // NIVEL BASICO: Estados React para gerenciar dados
  const [tables, setTables] = useState<string[]>([]);
  const [selectedTable, setSelectedTable] = useState<string>('');
  const [tableData, setTableData] = useState<Record<string, any>[]>([]);
  const [rowCount, setRowCount] = useState<number>(0);
  const [status, setStatus] = useState<string>('No database loaded');
  const [error, setError] = useState<string>('');

  // NIVEL BASICO: Carrega banco de dados
  async function loadDatabase() {
    try {
      setError('');
      setStatus('Loading...');

      // NIVEL BASICO: Chama metodo Go via Wails
      // NIVEL TECNICO: Empty string uses default path (data/sample.duckdb)
      const tableList = await window.go.main.App.LoadDatabase('');

      setTables(tableList);
      setStatus(`Loaded: sample.duckdb (${tableList.length} tables)`);

      // NIVEL BASICO: Carrega primeira tabela automaticamente
      if (tableList.length > 0) {
        await loadTable(tableList[0]);
      }
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : String(err);
      setError(errMsg);
      setStatus('Error loading database');
    }
  }

  // NIVEL BASICO: Carrega dados de uma tabela especifica
  async function loadTable(tableName: string) {
    try {
      setError('');
      setSelectedTable(tableName);

      // NIVEL BASICO: Busca dados e contagem em paralelo
      // NIVEL TECNICO: Promise.all for concurrent requests
      const [data, count] = await Promise.all([
        window.go.main.App.GetTableData(tableName, 100),
        window.go.main.App.GetRowCount(tableName),
      ]);

      setTableData(data);
      setRowCount(count);
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : String(err);
      setError(errMsg);
    }
  }

  // NIVEL BASICO: Pega nomes das colunas do primeiro row
  const columns = tableData.length > 0 ? Object.keys(tableData[0]) : [];

  return (
    <div className="container">
      <h1>MDB2SQL - Feature 1: Load and Display Table</h1>

      {/* NIVEL BASICO: Controles */}
      <div className="controls">
        <label>Table:</label>
        <select
          value={selectedTable}
          onChange={(e) => loadTable(e.target.value)}
          disabled={tables.length === 0}
        >
          {tables.map((table) => (
            <option key={table} value={table}>
              {table}
            </option>
          ))}
        </select>

        <button onClick={loadDatabase}>Load Database</button>

        <span className={error ? 'status error' : 'status success'}>
          {error || status}
        </span>
      </div>

      {/* NIVEL BASICO: Tabela de dados */}
      {tableData.length > 0 && (
        <div className="table-container">
          <table>
            <thead>
              <tr>
                {columns.map((col) => (
                  <th key={col}>{col}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {tableData.map((row, idx) => {
                // NIVEL BASICO: Cria key unica combinando valores da row
                // NIVEL TECNICO: Stable key prevents re-render issues
                const rowKey = row.UNIQID || row.id || `${selectedTable}_${idx}`;
                return (
                  <tr key={rowKey}>
                    {columns.map((col) => (
                      <td key={col}>{String(row[col] ?? '')}</td>
                    ))}
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {/* NIVEL BASICO: Info rodape */}
      {selectedTable && (
        <div className="info">
          {selectedTable}: Showing {tableData.length} of {rowCount} rows
        </div>
      )}
    </div>
  );
}

export default App;
